# Generated by Django 4.2.27 on 2025-12-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachingpost',
            options={'ordering': ['-created_on']},
        ),
    ]
