# Generated by Django 4.2.27 on 2025-12-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_progresscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresscomment',
            name='approved',
        ),
    ]
