# Generated by Django 4.2.27 on 2026-01-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coachingpost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscomment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
