# Generated by Django 4.2.27 on 2026-02-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_progresscomment_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachingpost',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='progresscomment',
            options={'ordering': ['-updated_on']},
        ),
    ]
