# Generated by Django 4.2.27 on 2026-01-21 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeconsultationrequest',
            options={'ordering': ['-read', '-created_on']},
        ),
        migrations.AddField(
            model_name='freeconsultationrequest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
