# Generated by Django 4.2.27 on 2026-02-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0002_alter_freeconsultationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeconsultationrequest',
            options={'ordering': ['read', '-created_on']},
        ),
    ]
